### ISSUE TITLE
Support Basic Authentication in API

### ISSUE THREAD

**Issue by ykohata** [tc3-japan/website-crawler#35]
The Product search API should support a simple basic authentication.
If a single pair of username and password is set in the application config, the API will ask clients to input it for accessing endpoints.

**Application YAML**
```
authentication:
  enabled: true
  credentials:
    username: admin
    password: adminpass
```
